from ..matter import periodic_table
from ..matter import geometry
from ..matter import atom
from ..matter import gmx
import common
import re

import numpy

def load(f, rename_atoms = {}, rename_mol={}):
    f = common.get_file_handle(f)
    comment = f.readline().rstrip()
    extras['comment'] = comment

    natoms = int(f.readline())

    geo = geometry.Geometry([])

    wmsplit = re.compile(r'(\d+)(\w+)')
    molnum_prev, mol_prev = -1,None
    for i in range(natoms):
        s = f.readline().split()
        
        # s[0] contains the molecule number and name
        m = wmsplit.search(s[0])
        molnum  = m.group(1)
        molname = m.group(2)
        # s[1] is the atom gmxname
        gmxname = s[1]
        if gmxname in rename_atoms:
            symbol = rename_atoms[gmxname]
        else:
            symbol = gmxname
        a = periodic_table.by_symbol(symbol)
        name = a.name if a else None
        number = a.number if a else None
        mass = a.mass if a else None
        

        # s[3:6] are coordinates in nm
        r = numpy.array(map(float, s[3:6])) * 10
        # s[6:10] are velocities in nm/ps
        v = numpy.array(map(float, s[6:10])) * 10
        atm = gmx.GMXAtom(symbol, name, number, mass, r, gmxname, v)
        
        if not mol_prev or molnum_prev != molnum:
            if molnum_prev != molnum:
                geo += mol_prev
            symbol, name = rename_mol[molname] if molname in rename_mol else [None, None]
            mol = gmx.GMXMolecule([], symbol, name, molnum, molname)
        else:
            mol = mol_prev
        mol += atm
        
        molnum_prev, mol_prev = molnum, mol

    geo += mol     

    f.close()
    return geo, extras

def save(f, geo, extras = {}):
    f, washandle = common.get_file_write_handle(f)
    allatoms = geo.get_atoms()
    print >> f, len(atoms)
    if 'comment' in extras:
        print >> f, extras['comment']
    else:
        print >> f, "Generated by struct"

    for i in atoms:
        print >> f, i.symbol, i.r[0], i.r[1], i.r[2]

    if not washangle:
        f.close()

