from ..matter import periodic_table
from ..matter import geometry
from ..matter import atom
from ..matter import gmx
import common
import re

import numpy

def load(f, rename_atoms = {}, rename_mol={}):
    f, washandle = common.get_file_read_handle(f)
    extras = {}
    comment = f.readline().rstrip()
    extras['comment'] = comment

    natoms = int(f.readline())

    geo = geometry.Geometry([])

    molnum_prev, mol_prev = -1,None
    for i in range(natoms):
        s = f.readline()
        
        # l[0:5] contains the molecule number
        molnum  = int(s[0:5])
        # l[5:10] contains the molecule name
        molname = s[5:10].strip()
        # s[10:15] is the atom gmxname
        gmxname = s[10:15].strip()
        if gmxname in rename_atoms:
            symbol = rename_atoms[gmxname]
        else:
            symbol = gmxname
        a = periodic_table.by_symbol(symbol)
        name = a.name if a else None
        number = a.number if a else None
        mass = a.mass if a else None
        

        # s[20:44] are coordinates in nm
        r = numpy.array(map(float, [s[20:28], s[28:36], s[36:44]])) * 10
        # s[44:68] are velocities in nm/ps
        if len(s)==68:
            v = numpy.array(map(float, [s[44:52], s[52:60], s[60:68]])) * 10
        else:
            v = numpy.zeros(3)
        atm = gmx.GMXAtom(symbol, name, number, mass, r, gmxname, v)
        
        if not mol_prev or molnum_prev != molnum:
            if mol_prev and molnum_prev != molnum:
                geo.append(mol_prev)
            symbol, name = rename_mol[molname] if molname in rename_mol else [None, None]
            mol = gmx.GMXMolecule([], symbol, name, molnum, molname)
        else:
            mol = mol_prev
        mol.append(atm)
        
        molnum_prev, mol_prev = molnum, mol

    geo.append(mol)     
    
    # last line is the box in nm
    geo.box = numpy.diag(numpy.array(map(float, f.readline().split()))*10)
    if not washandle:
        f.close()
    return geo, extras

def save(f, geo, extras = {}):
    f, washandle = common.get_file_write_handle(f)
    print >> f, extras['comment'] if 'comment' in extras else 'Generated by chemvert'
    print >> f, len(geo.get_atoms())
    count = 0
    for i, molecule in enumerate(geo.matter):
        for atom in molecule.get_atoms():
            count += 1
            print >> f, "%5d%-5s%5s%5d%8.3f%8.3f%8.3f" % (i+1, molecule.gmxsymbol, atom.gmxname, count, atom.r[0]/10, atom.r[1]/10, atom.r[2]/10),
            #XXX: really should do something about velocity printing
            if False:#atom.v is not None:
                print >> f, "%8.4f%8.4f%8.4f" % (atom.v[0]/10, atom.v[1]/10, atom.v[2]/10)
            else:
                print >> f
    if hasattr(geo,'box') and hasattr(geo.box,'shape') and geo.box.shape == (3,3):
        print >> f, geo.box[0,0]/10, geo.box[1,1]/10, geo.box[2,2]/10
    else:
        print >> f, "0.0 0.0 0.0"

    if not washandle:
        f.close()
        


